server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/hypothyro
    username: postgres
    password: password
  jpa:  
    hibernate:  
      ddl-auto: update  
    database-platform: org.hibernate.dialect.PostgreSQLDialect


