package com.github.hypothyro.domain;

public enum PatientState {
    REGISTRATION_NAME,
    REGISTRATION_DOB,
    REGISTRATION_GENDER,
    REGISTRATION_WEIGHT,
    REGISTRATION_PREGNANT,
    REGISTRATION_PRETREATMENT_MKG,
    REGISTRATION_PRETREATMENT_NAME,
    REGISTRATION_DOP,
    REGISTRATION_OP,
    REGISTRATION_TREATMENT_MKG,
    REGISTRATION_TREATMENT_NAME,
    REGISTRATION_FINISH,
    REGISTRATION_EVALUATION,
    REGISTRATION_TTG_DATE,
    REGISTRATION_TTG_RESULT,
    NOTIFICATIONS,
    BASIC,
    AWAY
}
